export {
  staticTestimonials,
  staticTeam,
  staticAwards,
  workspaceApi,
  leadApi,
  siteApi,
  type WorkspaceFilters,
  type Partner,
  type Testimonial,
  type FAQ,
  type TeamMember,
  type Award,
  type LeadPayload,
} from "./staticData";